#!/usr/bin/env python3
"""Convert Markdown report to Word document"""

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
import sys

# Read the markdown file
with open('/home/skillman85/.openclaw/workspace/APP_IDEAS_REPORT_DEEP.md', 'r') as f:
    content = f.read()

# Create new Document
doc = Document()

# Title
title = doc.add_heading('App Store Opportunities Research Report', 0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER

# Subtitle
subtitle = doc.add_paragraph('Deep Dive - February 2, 2026')
subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

doc.add_paragraph('Generated by Marv - AI Assistant and Chief of Staff')
doc.add_paragraph('Time Invested: ~2 hours of comprehensive research')
doc.add_paragraph()

# Parse markdown and add to document
lines = content.split('\n')
in_list = False
list_items = []

for line in lines:
    line = line.strip()
    
    # Skip empty lines and markdown dividers
    if not line or line == '---':
        continue
    
    # Headers
    if line.startswith('# '):
        doc.add_heading(line[2:], 0)
    elif line.startswith('## '):
        doc.add_heading(line[3:], 1)
    elif line.startswith('### '):
        doc.add_heading(line[4:], 2)
    elif line.startswith('#### '):
        doc.add_heading(line[5:], 3)
    
    # Blockquotes (research notes)
    elif line.startswith('> '):
        quote = doc.add_paragraph(line[2:])
        quote.style = 'Quote'
    
    # Bullet points
    elif line.startswith('- ') or line.startswith('* '):
        if not in_list:
            doc.add_paragraph()
            in_list = True
        item = doc.add_paragraph(line[2:], style='List Bullet')
    
    # Numbered lists
    elif line[0:2].isdigit() and line[2:4] == '. ':
        if not in_list:
            doc.add_paragraph()
            in_list = True
        item = doc.add_paragraph(line[4:], style='List Number')
    
    # Regular paragraphs
    elif not line.startswith('#'):
        # Clean up bold/italic markdown
        clean_line = line.replace('**', '').replace('*', '').replace('`', '')
        if clean_line:
            p = doc.add_paragraph(clean_line)
    
    else:
        in_list = False

# Save document
doc.save('/home/skillman85/.openclaw/workspace/APP_IDEAS_REPORT.docx')
print("Word document created: /home/skillman85/.openclaw/workspace/APP_IDEAS_REPORT.docx")
